=== SnehitaAmara/EP-skilling/ep_skilling/WebContent/skill1_XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="student_details">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="student" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:float" name="no" />
							<xs:element type="xs:string" name="name" />
							<xs:element type="xs:string" name="email" />
							<xs:element type="xs:float" name="marks" />
							<xs:element type="xs:string" name="class" />
						</xs:sequence>
						<xs:attribute type="xs:string" name="id"
							use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SnehitaAmara/EP-skilling/ep_skilling/WebContent/skill1_xml.xml
<?xml version="1.0" encoding="UTF-8"?>



<?xml-stylesheet type="text/xsl" href="skill1_xsl.xsl"?>

<student_details xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="skill1_XMLSchema.xsd" >



	<student id ="a">
		<no> 11223 </no>
		<name> Snehita </name>
		<email> snehita@gmail.com</email>
		<marks> 90 </marks>
		<class> A </class>
	</student>

	<student id="b">
		<no> 10982 </no>
		<name> Chitra </name>
		<email> chitra@gmail.com</email>
		<marks> 89 </marks>
		<class> B </class>
	</student>

	<student id="c">
		<no> 20316 </no>
		<name> nishita </name>
		<email> nishita11@gmail.com</email>
		<marks> 91 </marks>
		<class> A </class>
	</student>

	<student id="d">
		<no> 28901 </no>
		<name> priya </name>
		<email> priya123@gmail.com</email>
		<marks> 92 </marks>
		<class> C </class>
	</student>

	<student id="e">
		<no> 32754 </no>
		<name> Ramya </name>
		<email> ramya13@gmail.com</email>
		<marks> 88 </marks>
		<class> A </class>
	</student>

</student_details>
